//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosyblueonline.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rosyblueonline.Web.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3EX | 3VG+.
        /// </summary>
        public static string _3EX3VG {
            get {
                return ResourceManager.GetString("3EX3VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Stock.
        /// </summary>
        public static string Active_Stock {
            get {
                return ResourceManager.GetString("Active_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bestdeal.
        /// </summary>
        public static string Add_Bestdeal {
            get {
                return ResourceManager.GetString("Add_Bestdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string Add_Customer {
            get {
                return ResourceManager.GetString("Add_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lab.
        /// </summary>
        public static string Add_Lab {
            get {
                return ResourceManager.GetString("Add_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Roles &amp; Rights.
        /// </summary>
        public static string Add_Roles__Rights {
            get {
                return ResourceManager.GetString("Add_Roles__Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string Add_User {
            get {
                return ResourceManager.GetString("Add_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less : Additional Discount.
        /// </summary>
        public static string Additional_Discount {
            get {
                return ResourceManager.GetString("Additional_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Address_Line_1 {
            get {
                return ResourceManager.GetString("Address_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Address_Line_2 {
            get {
                return ResourceManager.GetString("Address_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVANCE SEARCH.
        /// </summary>
        public static string ADVANCE_SEARCH {
            get {
                return ResourceManager.GetString("ADVANCE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Memo.
        /// </summary>
        public static string All_Memo {
            get {
                return ResourceManager.GetString("All_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        public static string All_Orders {
            get {
                return ResourceManager.GetString("All_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: All Orders are in USD..
        /// </summary>
        public static string All_Orders_are_in_USD {
            get {
                return ResourceManager.GetString("All_Orders_are_in_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Assigned.
        /// </summary>
        public static string Already_Assigned {
            get {
                return ResourceManager.GetString("Already_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount .
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (US$).
        /// </summary>
        public static string Amount_US {
            get {
                return ResourceManager.GetString("Amount_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountN {
            get {
                return ResourceManager.GetString("AmountN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Discount (%).
        /// </summary>
        public static string Avg_Discount {
            get {
                return ResourceManager.GetString("Avg_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.($)/ct.
        /// </summary>
        public static string Avgct {
            get {
                return ResourceManager.GetString("Avgct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.Rap Price ($).
        /// </summary>
        public static string AvgRap_Price {
            get {
                return ResourceManager.GetString("AvgRap_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string Bank_Name {
            get {
                return ResourceManager.GetString("Bank_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Change.
        /// </summary>
        public static string Before_Change {
            get {
                return ResourceManager.GetString("Before_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST DEAL.
        /// </summary>
        public static string BEST_DEAL {
            get {
                return ResourceManager.GetString("BEST_DEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Site.
        /// </summary>
        public static string Block_Site {
            get {
                return ResourceManager.GetString("Block_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Nile.
        /// </summary>
        public static string Blue_Nile {
            get {
                return ResourceManager.GetString("Blue_Nile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Nile Disc %.
        /// </summary>
        public static string Blue_Nile_Disc {
            get {
                return ResourceManager.GetString("Blue_Nile_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueNile Disc%.
        /// </summary>
        public static string BlueNile_Disc {
            get {
                return ResourceManager.GetString("BlueNile_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Name.
        /// </summary>
        public static string Box_Name {
            get {
                return ResourceManager.GetString("Box_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Full Memo.
        /// </summary>
        public static string Cancel_Full_Memo {
            get {
                return ResourceManager.GetString("Cancel_Full_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Memo.
        /// </summary>
        public static string Cancel_Memo {
            get {
                return ResourceManager.GetString("Cancel_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CentreBlack.
        /// </summary>
        public static string CentreBlack {
            get {
                return ResourceManager.GetString("CentreBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cert. No..
        /// </summary>
        public static string Cert_No {
            get {
                return ResourceManager.GetString("Cert_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cert Number to Search.
        /// </summary>
        public static string Cert_Number_to_Search {
            get {
                return ResourceManager.GetString("Cert_Number_to_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CERTIFICATE.
        /// </summary>
        public static string CERTIFICATE {
            get {
                return ResourceManager.GetString("CERTIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate No.
        /// </summary>
        public static string Certificate_No {
            get {
                return ResourceManager.GetString("Certificate_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate#.
        /// </summary>
        public static string CertificateId {
            get {
                return ResourceManager.GetString("CertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change discount.
        /// </summary>
        public static string Change_discount {
            get {
                return ResourceManager.GetString("Change_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change rap.
        /// </summary>
        public static string Change_rap {
            get {
                return ResourceManager.GetString("Change_rap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarity.
        /// </summary>
        public static string Clarity {
            get {
                return ResourceManager.GetString("Clarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        public static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNR Disc.
        /// </summary>
        public static string CNR_Disc {
            get {
                return ResourceManager.GetString("CNR_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNR Disc HA.
        /// </summary>
        public static string CNR_Disc_HA {
            get {
                return ResourceManager.GetString("CNR_Disc_HA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string Create_Date {
            get {
                return ResourceManager.GetString("Create_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Created_By {
            get {
                return ResourceManager.GetString("Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Dae.
        /// </summary>
        public static string Created_Dae {
            get {
                return ResourceManager.GetString("Created_Dae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string Created_On {
            get {
                return ResourceManager.GetString("Created_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrownAngle.
        /// </summary>
        public static string CrownAngle {
            get {
                return ResourceManager.GetString("CrownAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrownHeight.
        /// </summary>
        public static string CrownHeight {
            get {
                return ResourceManager.GetString("CrownHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string Current_Status {
            get {
                return ResourceManager.GetString("Current_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Demands.
        /// </summary>
        public static string Customer_Demands {
            get {
                return ResourceManager.GetString("Customer_Demands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Recent Search.
        /// </summary>
        public static string Customer_Recent_Search {
            get {
                return ResourceManager.GetString("Customer_Recent_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Update.
        /// </summary>
        public static string Customer_Update {
            get {
                return ResourceManager.GetString("Customer_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUT - POLISH - SYMMETRY.
        /// </summary>
        public static string CUT_POLISH_SYMMETRY {
            get {
                return ResourceManager.GetString("CUT_POLISH_SYMMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Name.
        /// </summary>
        public static string Demand_Name {
            get {
                return ResourceManager.GetString("Demand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demands.
        /// </summary>
        public static string Demands {
            get {
                return ResourceManager.GetString("Demands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth%.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamentions.
        /// </summary>
        public static string Diamentions {
            get {
                return ResourceManager.GetString("Diamentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Inventory.
        /// </summary>
        public static string Disable_Inventory {
            get {
                return ResourceManager.GetString("Disable_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set differential discount for Blue-Nile upload data.
        /// </summary>
        public static string Discount_for_BlueNile_upload_data {
            get {
                return ResourceManager.GetString("Discount_for_BlueNile_upload_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set differential discount for James Allen Hong Kong&apos;s upload.
        /// </summary>
        public static string Discount_for_James_Allen_Hong_Kong_upload {
            get {
                return ResourceManager.GetString("Discount_for_James_Allen_Hong_Kong_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set differential discount for James Allen upload data.
        /// </summary>
        public static string Discount_for_James_Allen_upload_data {
            get {
                return ResourceManager.GetString("Discount_for_James_Allen_upload_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not Contains.
        /// </summary>
        public static string Does_not_Contains {
            get {
                return ResourceManager.GetString("Does_not_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download sample file for upload..
        /// </summary>
        public static string Download_sample_file_for_upload {
            get {
                return ResourceManager.GetString("Download_sample_file_for_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/R.
        /// </summary>
        public static string DR {
            get {
                return ResourceManager.GetString("DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC.
        /// </summary>
        public static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Inventory.
        /// </summary>
        public static string Enable_Inventory {
            get {
                return ResourceManager.GetString("Enable_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Cert Number.
        /// </summary>
        public static string Enter_Cert_Number {
            get {
                return ResourceManager.GetString("Enter_Cert_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Lot Numaber.
        /// </summary>
        public static string Enter_Lot_Numaber {
            get {
                return ResourceManager.GetString("Enter_Lot_Numaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Download.
        /// </summary>
        public static string Excel_Download {
            get {
                return ResourceManager.GetString("Excel_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string Export_to_Excel {
            get {
                return ResourceManager.GetString("Export_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add : Extra Charges (100$ will be charged because the order is below $ 10,000 ).
        /// </summary>
        public static string Extra_Charges {
            get {
                return ResourceManager.GetString("Extra_Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANCY COLOR.
        /// </summary>
        public static string FANCY_COLOR {
            get {
                return ResourceManager.GetString("FANCY_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANCY SHAPE.
        /// </summary>
        public static string FANCY_SHAPE {
            get {
                return ResourceManager.GetString("FANCY_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ID.
        /// </summary>
        public static string File_ID {
            get {
                return ResourceManager.GetString("File_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string File_Type {
            get {
                return ResourceManager.GetString("File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Role.
        /// </summary>
        public static string Filter_By_Role {
            get {
                return ResourceManager.GetString("Filter_By_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flora.
        /// </summary>
        public static string Flora {
            get {
                return ResourceManager.GetString("Flora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLUORESCENCE.
        /// </summary>
        public static string FLUORESCENCE {
            get {
                return ResourceManager.GetString("FLUORESCENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password?.
        /// </summary>
        public static string Forget_Password {
            get {
                return ResourceManager.GetString("Forget_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Total.
        /// </summary>
        public static string Found_Total {
            get {
                return ResourceManager.GetString("Found_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIA Reports.
        /// </summary>
        public static string GIA_Reports {
            get {
                return ResourceManager.GetString("GIA_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIAcomments.
        /// </summary>
        public static string GIAcomments {
            get {
                return ResourceManager.GetString("GIAcomments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdle.
        /// </summary>
        public static string Girdle {
            get {
                return ResourceManager.GetString("Girdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdle%.
        /// </summary>
        public static string Girdle_Per {
            get {
                return ResourceManager.GetString("Girdle_Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H&amp;A.
        /// </summary>
        public static string HA {
            get {
                return ResourceManager.GetString("HA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA-Ex Disc.
        /// </summary>
        public static string HA_Ex_Disc {
            get {
                return ResourceManager.GetString("HA-Ex_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA-VG Disc.
        /// </summary>
        public static string HA_VG_Disc {
            get {
                return ResourceManager.GetString("HA-VG_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts &amp; Arrows.
        /// </summary>
        public static string Hearts__Arrows {
            get {
                return ResourceManager.GetString("Hearts__Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosy Blue is one of the most renowned diamond and jewelry companies in the world. From rough to polished diamonds to fine jewelry, Rosy Blue&apos;s passion for excellence sparkles in everything we do. We operate in strict compliance with the Kimberley Process Certification Scheme and the World Diamond Council System of Warranties..
        /// </summary>
        public static string HomePage_Para1 {
            get {
                return ResourceManager.GetString("HomePage_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Download.
        /// </summary>
        public static string Inventory_Download {
            get {
                return ResourceManager.GetString("Inventory_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory on Memo.
        /// </summary>
        public static string Inventory_on_Memo {
            get {
                return ResourceManager.GetString("Inventory_on_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Upload.
        /// </summary>
        public static string Inventory_Upload {
            get {
                return ResourceManager.GetString("Inventory_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Count.
        /// </summary>
        public static string Item_Count {
            get {
                return ResourceManager.GetString("Item_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JA BN Partition.
        /// </summary>
        public static string JA_BN_Partition {
            get {
                return ResourceManager.GetString("JA_BN_Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James Allen.
        /// </summary>
        public static string James_Allen {
            get {
                return ResourceManager.GetString("James_Allen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James Allen Disc %.
        /// </summary>
        public static string James_Allen_Disc {
            get {
                return ResourceManager.GetString("James_Allen_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James Allen HK.
        /// </summary>
        public static string James_Allen_HK {
            get {
                return ResourceManager.GetString("James_Allen_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James Allen HK Disc %.
        /// </summary>
        public static string James_Allen_HK_Disc {
            get {
                return ResourceManager.GetString("James_Allen_HK_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JamesAllen Disc%.
        /// </summary>
        public static string JamesAllen_Disc {
            get {
                return ResourceManager.GetString("JamesAllen_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JamesAllen HK Disc%.
        /// </summary>
        public static string JamesAllen_HK_Disc {
            get {
                return ResourceManager.GetString("JamesAllen_HK_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key To Symbols.
        /// </summary>
        public static string Key_To_Symbols {
            get {
                return ResourceManager.GetString("Key_To_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytosymbol.
        /// </summary>
        public static string Keytosymbol {
            get {
                return ResourceManager.GetString("Keytosymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser.
        /// </summary>
        public static string Laser {
            get {
                return ResourceManager.GetString("Laser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        public static string List_Name {
            get {
                return ResourceManager.GetString("List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Customers.
        /// </summary>
        public static string List_of_Customers {
            get {
                return ResourceManager.GetString("List_of_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Result.
        /// </summary>
        public static string Load_Result {
            get {
                return ResourceManager.GetString("Load_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot No.
        /// </summary>
        public static string Lot_No {
            get {
                return ResourceManager.GetString("Lot_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number to Search.
        /// </summary>
        public static string Lot_Number_to_Search {
            get {
                return ResourceManager.GetString("Lot_Number_to_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot/Cret. No.
        /// </summary>
        public static string LotCret_No {
            get {
                return ResourceManager.GetString("LotCret_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerHalf.
        /// </summary>
        public static string LowerHalf {
            get {
                return ResourceManager.GetString("LowerHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rights.
        /// </summary>
        public static string Manage_Rights {
            get {
                return ResourceManager.GetString("Manage_Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMO.
        /// </summary>
        public static string MEMO {
            get {
                return ResourceManager.GetString("MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo No.
        /// </summary>
        public static string Memo_No {
            get {
                return ResourceManager.GetString("Memo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Pending.
        /// </summary>
        public static string Memo_Pending {
            get {
                return ResourceManager.GetString("Memo_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Sold.
        /// </summary>
        public static string Memo_Sold {
            get {
                return ResourceManager.GetString("Memo_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milky.
        /// </summary>
        public static string Milky {
            get {
                return ResourceManager.GetString("Milky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Inventory.
        /// </summary>
        public static string Modify_Inventory {
            get {
                return ResourceManager.GetString("Modify_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Demands.
        /// </summary>
        public static string Multiple_Demands {
            get {
                return ResourceManager.GetString("Multiple_Demands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string My_Account {
            get {
                return ResourceManager.GetString("My_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Order.
        /// </summary>
        public static string My_Order {
            get {
                return ResourceManager.GetString("My_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string New_Customer {
            get {
                return ResourceManager.GetString("New_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Upload.
        /// </summary>
        public static string New_Upload {
            get {
                return ResourceManager.GetString("New_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User?Please Register Here.
        /// </summary>
        public static string New_UserPlease_Register_Here {
            get {
                return ResourceManager.GetString("New_UserPlease_Register_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO BGM.
        /// </summary>
        public static string NO_BGM {
            get {
                return ResourceManager.GetString("NO_BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of file Chosen.
        /// </summary>
        public static string No_of_file_Chosen {
            get {
                return ResourceManager.GetString("No_of_file_Chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Memo.
        /// </summary>
        public static string On_Memo {
            get {
                return ResourceManager.GetString("On_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less : Online Discount.
        /// </summary>
        public static string Online_Discount {
            get {
                return ResourceManager.GetString("Online_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnMemo.
        /// </summary>
        public static string OnMemo {
            get {
                return ResourceManager.GetString("OnMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        public static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens.
        /// </summary>
        public static string Opens {
            get {
                return ResourceManager.GetString("Opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Order_Date {
            get {
                return ResourceManager.GetString("Order_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string Order_Details {
            get {
                return ResourceManager.GetString("Order_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Order_ID {
            get {
                return ResourceManager.GetString("Order_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        public static string Order_No {
            get {
                return ResourceManager.GetString("Order_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Pending.
        /// </summary>
        public static string Order_Pending {
            get {
                return ResourceManager.GetString("Order_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string Order_Status {
            get {
                return ResourceManager.GetString("Order_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial memo cancel.
        /// </summary>
        public static string Partial_memo_cancel {
            get {
                return ResourceManager.GetString("Partial_memo_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PavilionAngle.
        /// </summary>
        public static string PavilionAngle {
            get {
                return ResourceManager.GetString("PavilionAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PavilionDepth.
        /// </summary>
        public static string PavilionDepth {
            get {
                return ResourceManager.GetString("PavilionDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Order Details.
        /// </summary>
        public static string Pending_Order_Details {
            get {
                return ResourceManager.GetString("Pending_Order_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Order Report.
        /// </summary>
        public static string Pending_Order_Report {
            get {
                return ResourceManager.GetString("Pending_Order_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Orders.
        /// </summary>
        public static string Pending_Orders {
            get {
                return ResourceManager.GetString("Pending_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Stock.
        /// </summary>
        public static string Physical_Stock {
            get {
                return ResourceManager.GetString("Physical_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price($)/ct.
        /// </summary>
        public static string Pricect {
            get {
                return ResourceManager.GetString("Pricect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put on memo/sell directly.
        /// </summary>
        public static string Put_on_memosell_directly {
            get {
                return ResourceManager.GetString("Put_on_memosell_directly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapDisc(%).
        /// </summary>
        public static string RapDisc {
            get {
                return ResourceManager.GetString("RapDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapPrice.
        /// </summary>
        public static string RapPrice {
            get {
                return ResourceManager.GetString("RapPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less : RB Discount.
        /// </summary>
        public static string RB_Discount {
            get {
                return ResourceManager.GetString("RB_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent RFID Count.
        /// </summary>
        public static string Recent_RFID_Count {
            get {
                return ResourceManager.GetString("Recent_RFID_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Search.
        /// </summary>
        public static string Recent_Search {
            get {
                return ResourceManager.GetString("Recent_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        public static string records {
            get {
                return ResourceManager.GetString("records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle RFID.
        /// </summary>
        public static string Recycle_RFID {
            get {
                return ResourceManager.GetString("Recycle_RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Bestdeal.
        /// </summary>
        public static string Remove_Bestdeal {
            get {
                return ResourceManager.GetString("Remove_Bestdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Lab.
        /// </summary>
        public static string Remove_Lab {
            get {
                return ResourceManager.GetString("Remove_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Order Item.
        /// </summary>
        public static string Remove_Order_Item {
            get {
                return ResourceManager.GetString("Remove_Order_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportDate.
        /// </summary>
        public static string ReportDate {
            get {
                return ResourceManager.GetString("ReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURN SALE.
        /// </summary>
        public static string RETURN_SALE {
            get {
                return ResourceManager.GetString("RETURN_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID.
        /// </summary>
        public static string RFID {
            get {
                return ResourceManager.GetString("RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID History.
        /// </summary>
        public static string RFID_History {
            get {
                return ResourceManager.GetString("RFID_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Master.
        /// </summary>
        public static string RFID_Master {
            get {
                return ResourceManager.GetString("RFID_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Modify.
        /// </summary>
        public static string RFID_Modify {
            get {
                return ResourceManager.GetString("RFID_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID No.
        /// </summary>
        public static string RFID_No {
            get {
                return ResourceManager.GetString("RFID_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfid Number.
        /// </summary>
        public static string Rfid_Number {
            get {
                return ResourceManager.GetString("Rfid_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Search.
        /// </summary>
        public static string RFID_Search {
            get {
                return ResourceManager.GetString("RFID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Stock Tally.
        /// </summary>
        public static string RFID_Stock_Tally {
            get {
                return ResourceManager.GetString("RFID_Stock_Tally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©RosyBlue, 2020.
        /// </summary>
        public static string RosyBlue_2020 {
            get {
                return ResourceManager.GetString("RosyBlue_2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUND SHAPE.
        /// </summary>
        public static string ROUND_SHAPE {
            get {
                return ResourceManager.GetString("ROUND_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES LOCATION.
        /// </summary>
        public static string SALES_LOCATION {
            get {
                return ResourceManager.GetString("SALES_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesLocation.
        /// </summary>
        public static string SalesLocation {
            get {
                return ResourceManager.GetString("SalesLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Search.
        /// </summary>
        public static string Save_Search {
            get {
                return ResourceManager.GetString("Save_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seand a Email.
        /// </summary>
        public static string Seand_a_Email {
            get {
                return ResourceManager.GetString("Seand_a_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select (.xlsx) file for RFID master.
        /// </summary>
        public static string Select__file_for_RFID_master {
            get {
                return ResourceManager.GetString("Select__file_for_RFID_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select (.xlxs) file to Update RFID.
        /// </summary>
        public static string Select__xlxs__file_to_Update_RFID {
            get {
                return ResourceManager.GetString("Select_(xlxs)_file_to_Update_RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select csv file to upload.
        /// </summary>
        public static string Select_csv_file_to_upload {
            get {
                return ResourceManager.GetString("Select_csv_file_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string Select_file {
            get {
                return ResourceManager.GetString("Select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select (.xlsx) file for upload GIA.
        /// </summary>
        public static string Select_file_for_upload_GIA {
            get {
                return ResourceManager.GetString("Select_file_for_upload_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file to upload.
        /// </summary>
        public static string Select_file_to_upload {
            get {
                return ResourceManager.GetString("Select_file_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sales Location.
        /// </summary>
        public static string Select_Sales_Location {
            get {
                return ResourceManager.GetString("Select_Sales_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to download sample file.
        /// </summary>
        public static string Select_to_download_sample_file {
            get {
                return ResourceManager.GetString("Select_to_download_sample_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string Select_Type {
            get {
                return ResourceManager.GetString("Select_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your choice.
        /// </summary>
        public static string Select_your_choice {
            get {
                return ResourceManager.GetString("Select_your_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Full Memo.
        /// </summary>
        public static string Sell_Full_Memo {
            get {
                return ResourceManager.GetString("Sell_Full_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Partial.
        /// </summary>
        public static string Sell_Partial {
            get {
                return ResourceManager.GetString("Sell_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade.
        /// </summary>
        public static string Shade {
            get {
                return ResourceManager.GetString("Shade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add : Shipping Charges Non India.
        /// </summary>
        public static string Shipping_Charges_Non_India {
            get {
                return ResourceManager.GetString("Shipping_Charges_Non_India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Company.
        /// </summary>
        public static string Shipping_Company {
            get {
                return ResourceManager.GetString("Shipping_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Mode 1.
        /// </summary>
        public static string Shipping_Mode_1 {
            get {
                return ResourceManager.GetString("Shipping_Mode_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site not blocked.
        /// </summary>
        public static string Site_not_blocked {
            get {
                return ResourceManager.GetString("Site_not_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE (CARATS).
        /// </summary>
        public static string SIZE_CARATS {
            get {
                return ResourceManager.GetString("SIZE_CARATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specfic search.
        /// </summary>
        public static string Specfic_search {
            get {
                return ResourceManager.GetString("Specfic_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIFIC SEARCH.
        /// </summary>
        public static string SPECIFIC_SEARCH {
            get {
                return ResourceManager.GetString("SPECIFIC_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Memo.
        /// </summary>
        public static string Split_Memo {
            get {
                return ResourceManager.GetString("Split_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starlength.
        /// </summary>
        public static string Starlength {
            get {
                return ResourceManager.GetString("Starlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock &amp; Summary.
        /// </summary>
        public static string Stock__Summary {
            get {
                return ResourceManager.GetString("Stock__Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Details.
        /// </summary>
        public static string Stock_Details {
            get {
                return ResourceManager.GetString("Stock_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Summary.
        /// </summary>
        public static string Stock_Summary {
            get {
                return ResourceManager.GetString("Stock_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock tally.
        /// </summary>
        public static string Stock_tally {
            get {
                return ResourceManager.GetString("Stock_tally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone History.
        /// </summary>
        public static string Stone_History {
            get {
                return ResourceManager.GetString("Stone_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone IDs.
        /// </summary>
        public static string Stone_IDs {
            get {
                return ResourceManager.GetString("Stone_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Status.
        /// </summary>
        public static string Stone_Status {
            get {
                return ResourceManager.GetString("Stone_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry.
        /// </summary>
        public static string Symmetry {
            get {
                return ResourceManager.GetString("Symmetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less : System discount 0K-15K.
        /// </summary>
        public static string System_discount_K {
            get {
                return ResourceManager.GetString("System_discount_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table%.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableBlack.
        /// </summary>
        public static string TableBlack {
            get {
                return ResourceManager.GetString("TableBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amt.
        /// </summary>
        public static string Total_Amt {
            get {
                return ResourceManager.GetString("Total_Amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total CT.
        /// </summary>
        public static string Total_CT {
            get {
                return ResourceManager.GetString("Total_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Inventory.
        /// </summary>
        public static string Total_Inventory {
            get {
                return ResourceManager.GetString("Total_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payable Amount :.
        /// </summary>
        public static string Total_Payable_Amount {
            get {
                return ResourceManager.GetString("Total_Payable_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rap Price ($).
        /// </summary>
        public static string Total_Rap_Price {
            get {
                return ResourceManager.GetString("Total_Rap_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total RFID Count.
        /// </summary>
        public static string Total_RFID_Count {
            get {
                return ResourceManager.GetString("Total_RFID_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalFound.
        /// </summary>
        public static string TotalFound {
            get {
                return ResourceManager.GetString("TotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number.
        /// </summary>
        public static string Tracking_Number {
            get {
                return ResourceManager.GetString("Tracking_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnReferenced.
        /// </summary>
        public static string UnReferenced {
            get {
                return ResourceManager.GetString("UnReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string Upcoming_Events {
            get {
                return ResourceManager.GetString("Upcoming_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplaod Format Common.
        /// </summary>
        public static string Uplaod_Format_Common {
            get {
                return ResourceManager.GetString("Uplaod_Format_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplaod Inventory.
        /// </summary>
        public static string Uplaod_Inventory {
            get {
                return ResourceManager.GetString("Uplaod_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Add/Remove Lab Format.
        /// </summary>
        public static string Upload_Add_Remove_Lab_Format {
            get {
                return ResourceManager.GetString("Upload_Add_Remove_Lab_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Format Best Deal.
        /// </summary>
        public static string Upload_Format_Best_Deal {
            get {
                return ResourceManager.GetString("Upload_Format_Best_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload History.
        /// </summary>
        public static string Upload_History {
            get {
                return ResourceManager.GetString("Upload_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Inventory.
        /// </summary>
        public static string Upload_Inventory {
            get {
                return ResourceManager.GetString("Upload_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD LOT/CERT NUMBER TO SEARCH.
        /// </summary>
        public static string UPLOAD_LOTCERT_NUMBER_TO_SEARCH {
            get {
                return ResourceManager.GetString("UPLOAD_LOTCERT_NUMBER_TO_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload New Inventory.
        /// </summary>
        public static string Upload_New_Inventory {
            get {
                return ResourceManager.GetString("Upload_New_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Stone IDs.
        /// </summary>
        public static string Upload_Stone_IDs {
            get {
                return ResourceManager.GetString("Upload_Stone_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Date.
        /// </summary>
        public static string Uploaded_Date {
            get {
                return ResourceManager.GetString("Uploaded_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Detail.
        /// </summary>
        public static string User_Detail {
            get {
                return ResourceManager.GetString("User_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Vs Rights.
        /// </summary>
        public static string User_Vs_Rights {
            get {
                return ResourceManager.GetString("User_Vs_Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V360.
        /// </summary>
        public static string V360 {
            get {
                return ResourceManager.GetString("V360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V360 Via CERT No.
        /// </summary>
        public static string V360_Via_CERT_No {
            get {
                return ResourceManager.GetString("V360_Via_CERT_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Memo Details.
        /// </summary>
        public static string View_Memo_Details {
            get {
                return ResourceManager.GetString("View_Memo_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Order Details.
        /// </summary>
        public static string View_Order_Details {
            get {
                return ResourceManager.GetString("View_Order_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Pending Orders.
        /// </summary>
        public static string View_Pending_Orders {
            get {
                return ResourceManager.GetString("View_Pending_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sold History.
        /// </summary>
        public static string View_Sold_History {
            get {
                return ResourceManager.GetString("View_Sold_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Order Pending.
        /// </summary>
        public static string Website_Order_Pending {
            get {
                return ResourceManager.GetString("Website_Order_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Guest,.
        /// </summary>
        public static string Welcome_Guest {
            get {
                return ResourceManager.GetString("Welcome_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Rosy Blue.
        /// </summary>
        public static string Welcome_To_Rosy_Blue {
            get {
                return ResourceManager.GetString("Welcome_To_Rosy_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string Zip_Code {
            get {
                return ResourceManager.GetString("Zip_Code", resourceCulture);
            }
        }
    }
}
